services:
  app:
    logging:
      driver: json-file
      options:
        max-size: "10m"
        max-file: "3"
    build: .
    container_name: quotes-app
    ports:
      - "8050:8050"
    volumes:
      - ./data:/app/data
    env_file:
      - .env
    restart: unless-stopped
